CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY,
    tasks VARCHAR(255) NOT NULL,
    is_done BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP NOT NULL DEFAULT NOW()
);